/* eslint-disable */

export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const SET_ARTICLES_PAGE = 'SET_ARTICLES_PAGE';
export const SET_ONE_ARTICLE = 'SET_ONE_ARTICLE';
